#!/usr/bin/env python3
"""Merge truckstops/data/*.json state files into truckstops/data.js.

Run from anywhere:  python3 truckstops/build-data.py
"""
import json, glob, os, sys

here = os.path.dirname(os.path.abspath(__file__))
files = sorted(glob.glob(os.path.join(here, "data", "*.json")))
if not files:
    sys.exit("No state JSON files found in truckstops/data/")

merged, errors = {}, []
total_stops = total_hw = 0

for path in files:
    abbr = os.path.splitext(os.path.basename(path))[0]
    try:
        with open(path) as f:
            st = json.load(f)
    except Exception as e:
        errors.append(f"{abbr}: {e}")
        continue
    if "state" not in st or "interstates" not in st:
        errors.append(f"{abbr}: missing 'state' or 'interstates' key")
        continue
    # normalize + sort stops by mile marker ascending
    for hw, iv in st["interstates"].items():
        stops = iv.get("stops") or []
        for s in stops:
            try:
                s["mm"] = int(round(float(s.get("mm", 0))))
            except (TypeError, ValueError):
                s["mm"] = 0
        iv["stops"] = sorted(stops, key=lambda s: s["mm"])
        total_stops += len(stops)
        total_hw += 1
    merged[abbr] = st

out = os.path.join(here, "data.js")
with open(out, "w") as f:
    f.write("// Auto-generated by build-data.py — do not edit by hand.\n")
    f.write("window.TRUCKSTOP_DATA = ")
    json.dump(merged, f, separators=(",", ":"), sort_keys=True)
    f.write(";\n")

print(f"Wrote {out}: {len(merged)} states, {total_hw} interstate segments, {total_stops} stops")
if errors:
    print("ERRORS:")
    for e in errors:
        print("  -", e)
    sys.exit(1)
